### ISSUE TITLE
Base64 or not?

### ISSUE THREAD

**Issue by glen-84** [FusionAuth/fusionauth-contrib#8]
Why do the `ExampleCustomMD5SaltAppendedPasswordEncryptor` and `ExampleCustomMD5SaltedPasswordEncryptor` plugins return Base64, but the `ExamplePBDKF2HMACSHA1PasswordEncryptor` plugin doesn't? What is correct?

**Comment by mooreds** [comment]
It should be base64 encoded, as [documented here](https://fusionauth.io/docs/v1/tech/apis/users#import-users):

> password should contain only the password hash as a base64 encoded string. Depending on how your password database stores hashes, additional processing may be required. Please see the [Password Hashes](https://fusionauth.io/docs/v1/tech/apis/users#password-hashes) section for more information about importing particular password hashes.

It looks like the `ExamplePBDKF2HMACSHA1PasswordEncryptor` code is incorrect. I'll file an issue, thanks!
