### ISSUE TITLE
Update ExamplePBDKF2HMACSHA1PasswordEncryptor to return base64

### ISSUE THREAD

**Issue by mooreds** [FusionAuth/fusionauth-contrib#9]
As @glen-84 mentioned here: https://github.com/FusionAuth/fusionauth-contrib/issues/8

The `ExamplePBDKF2HMACSHA1PasswordEncryptor` class incorrectly returns base16. https://fusionauth.io/docs/v1/tech/apis/users#import-users clearly specifies that all hashes should be returned as base64. 

This is a bug and should be fixed.

**Comment by robotdan** [comment]
Why is this a bug? A custom plugin can (in theory) do whatever it wants. This is a specific example of a scheme we have encountered when assisting a customer import from a legacy database.

**Comment by glen-84** [comment]
How would you import a user if the import API requires base64 passwords? When signing in, wouldn't it then compare a base16 hash from the plugin with a base64 string in the database? (or does it base64-decode the database password first?)

I do apologize if I'm getting mixed up. This issue doesn't affect me, I was just trying to understand why they differed/how import would work in this case.

**Comment by robotdan** [comment]
Perhaps we should update the doc. 

The statement is mostly true. In general we want everything base64 encoded. But I believe the impl - in this case `ExamplePBDKF2HMACSHA1PasswordEncryptor` can do whatever it wants. 

The only real requirement I suppose is that it return an encoded set of bytes that we can store and read as a string. 

This exception to the base64 encoding would only apply to custom plugins. For example, if you have a legacy plugin that you are using to migrate users into FusionAuth that stores a hash hex encoded as is the case with the referenced plugin, it should work as long as the plugin returns the same encoded set of bytes that is used on the import. 

If we wanted to clarify this in doc, it would be to say something like :

> Unless you are using a custom plugin that does not utilize base64, the password hash should be base64 encoded. It is recommended to use a base64 encoded string, but if you are importing hashes from a legacy system that uses base16 (hex), or base32 encoding (etc) - you will need to import the hash in the same format the plugin produces. 

You could also re-encode all hashes into base64 and then write your plugin to use base64. So either methodology should work as far as I know.

**Comment by glen-84** [comment]
Ya, this line from the docs really threw me off:

> `password` should contain only the password hash as a base64 encoded string

I've just tested removing base64 from both my plugin and my import script, and it does appear to work. Thanks.

**Comment by mooreds** [comment]
Closing this out, as I submitted a doc PR which will hopefully make things clearer. 

Thanks @glen-84 for bringing this to our attention, sorry for the confusion!

**Comment by mooreds** [comment]
Doc PR should be live in a few minutes.
